version: "2"
services:
  
  pwn:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctftraining/suctf_2019_pwn_playfmt
    volumes:
      - ./tcpdump:/var/lib/tcpdump
    ports:
      - "10001:10000"
    environment:
      # 题目限制，flag长度不能太长
      - FLAG=flag{playfmt}
      - TCPDUMP_ENABLE=0
